# Generated by Django 5.1.5 on 2025-08-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Threater',
            new_name='Theater',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
