# Generated by Django 5.1.5 on 2025-08-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_threater_theater_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showtime',
            field=models.TimeField(null=True),
        ),
    ]
