# Generated by Django 5.1.5 on 2025-08-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_movie_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='showtime',
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='ticket.movie')),
            ],
        ),
    ]
