# Generated by Django 5.2.5 on 2025-09-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_seat_movie_duration_movie_release_date_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_available',
        ),
    ]
